#!/bin/bash
source /etc/profile
set -eou pipefail


function usage() {
  echo ""
  echo "Queue management for retrieving jobs from SQS."
  echo ""
  echo "Usage: ./check-queue"
  echo ""
}


function onerror() {
  restore_message $receipt
  exit 1
}
trap onerror EXIT


function delete_message() {
  local receipt=$1
  echo "Deleting message $receipt"
  aws sqs delete-message --queue-url $SQS_URL --receipt-handle $receipt
}


function restore_message() {
  local receipt=$1
  echo "Restoring message $receipt"
  aws sqs change-message-visibility --queue-url $SQS_URL --receipt-handle $receipt --visibility-timeout 0
}


function check_queue() {

  msg=$(aws sqs receive-message --queue-url $SQS_URL)

  if [ -z "$msg" ]; then
    return 0
  fi

  receipt=$(echo $msg | jq -r ".Messages[].ReceiptHandle")
  sceneid=$(echo $msg | jq -r ".Messages[].Body")

  su landsat -c "/usr/local/src/landsat-ingestor-stack/scripts/download $sceneid" \
    && delete_message $receipt \
    || restore_message $receipt
}

check_queue

trap - EXIT
exit 0