#!/bin/bash
source /etc/profile
set -eou pipefail
 
 
function usage() {
  echo ""
  echo "Download a Landsat scene from USGS."
  echo ""
  echo "Usage: ./download [entity id]"
  echo ""
}


entityid=${1:-}


if [[ -z $entityid ]]; then
  usage;
  exit 1;
fi


function onerror() {
  rm -f /mnt/entityid.tar.gz
  sleep $[ $RANDOM % 10 + 1]s
  exit 1
}
trap onerror EXIT
 
 
function download_landsat() {
  local entityid=$1

  echo "Requesting a download url for $entityid"
  url=$(usgs download-url --node EE LANDSAT_8_C1 $entityid --product STANDARD)

  echo "Downloading $entityid"
  dstpath=/mnt/$entityid.tar.gz
  curl --silent --fail "$url" -o "$dstpath"

  echo "Copying $entityid to $dstpath"
  aws s3 cp $dstpath s3://landsat-pds/tarq/ --acl public-read

  rm -f $dstpath
}
 
download_landsat $entityid
 
trap - EXIT
exit 0