#!/bin/bash
source /etc/profile
set -eou pipefail
 
 
function usage() {
  echo ""
  echo "Download a Landsat scene from USGS."
  echo ""
  echo "Usage: ./download [entity id]"
  echo ""
}


entityid=${1:-}


if [[ -z $entityid ]]; then
  usage;
  exit 1;
fi


function onerror() {
  rm -f /mnt/entityid.tar.gz
  sleep $[ $RANDOM % 20 + 1]s
  exit 1
}
trap onerror EXIT
 
 
function download_landsat() {
  local entityid=$1

  url=$(usgs download-url --node EE LANDSAT_8_C1 $entityid --product STANDARD | jq -r ".data[0].url")
  productid=$(echo "${url##*/}" | cut -d '.' -f1)
  dstpath=/mnt/$productid.tar.gz

  echo "Downloading $entityid from $url"
  t0=$(date +%s)
  curl --silent --fail "$url" -o "$dstpath"
  t1=$(date +%s)
  echo "Took $(($t1 - $t0)) seconds to download $entityid"

  echo "Copying $entityid to s3://landsat-pds/tarq/"
  aws s3 cp $dstpath s3://landsat-pds/tarq/ --acl public-read

  rm -f $dstpath
}
 
download_landsat $entityid
 
trap - EXIT
exit 0